---
# Hashtopolis server handlers

- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Restart Hashtopolis
  community.docker.docker_compose_v2:
    project_src: "{{ hashtopolis_dir }}"
    state: restarted
