---
# Global Variables for all hosts

# SSH Configuration
ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
ansible_python_interpreter: /usr/bin/python3

# Project settings
project_name: hashcrack
environment: lab

# Common packages
common_packages:
  - curl
  - wget
  - htop
  - vim
  - net-tools
  - jq
  - python3
  - python3-pip
