---
# Hashcrack Infrastructure - Master Playbook
# Configures Hashtopolis server and worker agents

- name: Configure all hosts with common settings
  hosts: all
  become: yes
  roles:
    - common

- name: Configure Hashtopolis server
  hosts: server
  become: yes
  roles:
    - hashtopolis_server
    - wordlists

- name: Configure Hashcat workers
  hosts: workers
  become: yes
  roles:
    - hashtopolis_agent
